const question1 = document.querySelector("#question-1");
const question2 = document.querySelector("#question-2");
const question3 = document.querySelector("#question-3");


const description = document.querySelector(".description");
const title = document.querySelector(".problem-title");


const questions = {
    "question-1":{
        title: "Multiples of 3 or 5",
        description: "If we list the natural numbers"+
        " below 10 that are multiples of 3 or 5, we get 3,5,6 and 9."+
        " The sum of these multiple is 23. Find the sum of all the multiples of 3 or 5 below "
    },
    "question-2":{
        title: "Even Fibonacci Numbers",
        description: "Each new term in the Fibonacci sequence is generated by adding the previous two terms."+
        " By starting with 1 and 2, the first 10 terms will be:"+
        " 1,2,3,5,8,13,21,34,55,89,..."+
        " By considering the terms in the Fibonacci sequence whose values"+
        " do not exceed four million, find the sum of the even-valued terms."
    },
    "question-3":{
        title: "Largest Prime Factor",
        description: "The prime factors of 13195 are 5,7,13 and 29"+
        " What is the largest prime factor of the number 600851475143?"
    }
}

question1.onclick = questionOne;
question2.onclick = questionTwo;
question3.onclick = questionThree;

function update(content){
    title.innerText = content.title;
    description.innerText = content.description;
}

function questionOneRandomMultipleNumber(){
    const min = 100;
    const max = 1000;

    const randomNumber = Math.floor(Math.random() * (max - min + 1) + min);

    const questionOneDescripSpan = document.createElement("span");
    questionOneDescripSpan.setAttribute("id", "questionOneRandomTargetValue");
    description.appendChild(questionOneDescripSpan);
    questionOneDescripSpan.textContent = randomNumber;
}

function questionOne(){
    update(questions["question-1"]);
    questionOneRandomMultipleNumber();
}

function questionTwo(){
    update(questions["question-2"]);
}

function questionThree(){
    update(questions["question-3"]);
}
