$(".content-section").hide();
$(".retry").hide();
$(".correct-response-icon").hide();
$(".wrong-response-icon").hide();

const questions = {
    "question-1":{
        title: "Multiples of 3 or 5",
        description: "If we list the natural numbers"+
        " below 10 that are multiples of 3 or 5, we get 3,5,6 and 9."+
        " The sum of these multiple is 23. Find the sum of all the multiples of 3 or 5 below the following value:"
    },
    "question-2":{
        title: "Even Fibonacci Numbers",
        description: "Each new term in the Fibonacci sequence is generated by adding the previous two terms."+
        " By starting with 1 and 2, the first 10 terms will be:"+
        " 1,2,3,5,8,13,21,34,55,89,..."+
        " By considering the terms in the Fibonacci sequence find the sum of the even-valued terms."+
        " Whose values do not exceed the following value: "
    },
    "question-3":{
        title: "Largest Prime Factor",
        description: "The prime factors of 13195 are 5,7,13 and 29"+
        " What is the largest prime factor of the following value:"
    }
}

$(".message-title").hide();
$(".message-title").fadeIn(10000);

// Onclick events for question tabs
$(".question-1").on("click", function(){
    update(questions["question-1"]);
});

$(".question-2").on("click", function(){
    update(questions["question-2"]);
});

$(".question-3").on("click", function(){
    update(questions["question-3"]);
});


//  OnClick event
$(".bi-arrow-clockwise").on("click", function(){
    showOrHide();
});

function showOrHide(){
    $(".retry").hide();
    $(".answer-response").hide();
    $("#answer-form").show();
}

function update(content){
    $(".welcome-message").hide();
    $(".content-section").show();
    $(".problem-title").text(content.title);
    $(".description").text(content.description);

    showOrHide()
}
